export const NavLinks = [
    {
        id:1,
        url:'/',
        label:'Home',
    }, 
    {
        id:2,
        url:'/projects',
        label:'Projects',
    }, 
    {
        id:3,
        url:'/about',
        label:'About',
    }, 
    {
        id:4,
        url:'/secret',
        label:'Secret',
    }
];